name: Deploy zstio-tv

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: self-hosted
    environment: Production

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Prepare pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          echo "/root/.local/share/pnpm/bin" >> $GITHUB_PATH
          npm config set store-dir .pnpm-store

      - name: Node Environment
        uses: actions/setup-node@4
        with:
          node-version: '22'
          cache: pnpm

      - name: Dependencies
        run: |
          pnpm install --frozen-lockfile
          npm install -g pm2

      - name: Setup environment variables
        run: |
          cat <<EOF > .env
          DATABASE_URL="file:./prisma.db"
          NEXTAUTH_URL=https://tv.ox80.me
          NEXTAUTH_SECRET=$(openssl rand -hex 128)
          SPOTIFY_ID=${{ secrets.SPOTIFY_ID }}
          SPOTIFY_SECRET=${{ secrets.SPOTIFY_SECRET }}
          SPOTIFY_REDIRECT=https://tv.ox80.me/api/spotify/auth
          EOF

      - name: Build
        run: pnpm build

      - name: Push to PM2
        run: |
          pm2 delete ZstioTv || true
          pm2 start pnpm --name ZstioTv -- start
          pm2 save
          pm2 startup
          pm2 save -f

      - name: Health Verification
        run: |
          pm2 list
          curl -sSf http://localhost:3000 -o /dev/null
