name: Deploy zstio-tv

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy application
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install global dependencies
        run: |
          npm install -g pnpm@latest pm2@latest
          pnpm --version
          pm2 --version

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile --prod=false

      - name: Setup environment variables
        run: |
          cat <<EOF > .env
          DATABASE_URL="file:./prisma.db"
          NEXTAUTH_URL=https://tv.ox80.me/
          NEXTAUTH_SECRET=$(openssl rand -hex 128)
          SPOTIFY_ID=${{ secrets.SPOTIFY_ID }}
          SPOTIFY_SECRET=${{ secrets.SPOTIFY_SECRET }}
          SPOTIFY_REDIRECT=http://tv.ox80.me/api/spotify/auth
          EOF

      - name: Build application
        run: pnpm build

      - name: Deploy with PM2
        run: |
          pm2 delete zstio-tv || true
          pm2 start npm --name zstio-tv -- run start
          
          pm2 save
          pm2 startup
          pm2 save --force

      - name: Verify deployment
        run: |
          pm2 list
          curl -I http://localhost:3000 || true
