name: Production

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.16.0]
    env:
      SPOTIFY_ID: ${{secrets.SPOTIFY_ID}}
      SPOTIFY_SECRET: ${{secrets.SPOTIFY_SECRET}}
      TURNSTILE_SECRET_KEY: ${{secrets.TURNSTILE_SECRET_KEY}}
      TURNSTILE_SITE_KEY: ${{secrets.TURNSTILE_SITE_KEY}}
      DATABASE_URL: "file:./prisma.db"
    steps:
    - uses: actions/checkout@v4
    
    - name: Install pnpm
      run: npm install -g pnpm
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    
    - name: Update lockfile
      run: pnpm install --lockfile-only
      
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Setup Database
      run: |
        if ! npx prisma db execute --url "$DATABASE_URL" --stdin < <(echo "SELECT 1"); then
          echo "Database doesn't exist - creating new database"
          npx prisma db push --accept-data-loss
        else
          echo "Database already exists - skipping creation"
        fi
        
    - name: Initialize Admin
      run: pnpm run init-admin
      
    - name: Build project
      run: pnpm run build
      
    - name: Install PM2 globally
      run: npm install -g pm2
      
    - name: Deploy with PM2
      run: |
        pm2 delete tv || true
        
        pm2 start pnpm --name "tv" -- start
        pm2 save
        
        pm2 startup | tail -n 1 | sudo sh
